import {
  faBomb,
  faFilm,
  faGhost,
  faHatCowboy,
  faHeart,
  faHeartbeat,
  faHiking,
  faHome,
  faLandmark,
  faLaugh,
  faMagic,
  faMagnifyingGlass,
  faMusic,
  faPersonRunning,
  faRobot,
  faTheaterMasks,
  faTv,
  faUserSecret,
  faVideo,
  faArrowRotateLeft,
} from "@fortawesome/free-solid-svg-icons";
import { Genre } from "../types/genre";

export const genres: Genre[] = [
  { id: 0, label: "All movies", icon: faArrowRotateLeft },
  {
    id: 28,
    label: "Action",
    icon: faPersonRunning,
  },
  { id: 12, label: "Adventure", icon: faHiking },
  { id: 16, label: "Animation", icon: faFilm },
  { id: 35, label: "Comedy", icon: faLaugh },
  { id: 80, label: "Crime", icon: faUserSecret },
  { id: 99, label: "Documentary", icon: faVideo },
  { id: 18, label: "Drama", icon: faTheaterMasks },
  { id: 10751, label: "Family", icon: faHome },
  { id: 14, label: "Fantasy", icon: faMagic },
  { id: 36, label: "History", icon: faLandmark },
  { id: 27, label: "Horror", icon: faGhost },
  { id: 10402, label: "Music", icon: faMusic },
  {
    id: 9648,
    label: "Mystery",
    icon: faMagnifyingGlass,
  },
  { id: 10749, label: "Romance", icon: faHeart },
  {
    id: 878,
    label: "Science Fiction",
    icon: faRobot,
  },
  { id: 10770, label: "TV Movie", icon: faTv },
  {
    id: 53,
    label: "Thriller",
    icon: faHeartbeat,
  },
  { id: 10752, label: "War", icon: faBomb },
  { id: 37, label: "Western", icon: faHatCowboy },
];
